// CSS build: copies each component file to dist/components/ and concatenates
// everything (tokens first) into dist/index.css for drop-in plain-HTML use.
import { mkdir, readFile, writeFile, readdir, rm, copyFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

// Order matters: primitives (state-layer) before components that compose them.
const ORDER = ["state-layer.css", "spinner.css", "button.css"];

const srcFiles = await readdir(path.join(root, "src"));
const unordered = srcFiles.filter((f) => f.endsWith(".css") && !ORDER.includes(f));
const files = [...ORDER.filter((f) => srcFiles.includes(f)), ...unordered];

await rm(path.join(root, "dist"), { recursive: true, force: true });
await mkdir(path.join(root, "dist/components"), { recursive: true });

const tokensCss = require.resolve("@ds/tokens/css");
const parts = [await readFile(tokensCss, "utf8")];

for (const file of files) {
  const from = path.join(root, "src", file);
  await copyFile(from, path.join(root, "dist/components", file));
  parts.push(await readFile(from, "utf8"));
}

await writeFile(
  path.join(root, "dist/index.css"),
  "/* Generated by @ds/css — tokens + all components. */\n\n" + parts.join("\n")
);

console.log(`@ds/css built: ${files.length} components`);
